<a href="https://colab.research.google.com/github/kimjaewoo1207/2026_1_BDA/blob/main/%EB%B9%85%EB%8D%B0%EC%9D%B4%ED%84%B0%EB%B6%84%EC%84%9D%ED%94%84%EB%A1%9C%EA%B7%B8%EB%9E%98%EB%B0%8D3%EC%A3%BC%EC%B0%A8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np

a = np.ndarray((2, 3))
a

array([[9.48164069e-316, 0.00000000e+000, 6.69815408e-310],
       [5.36368732e-317, 5.37026432e-317, 6.69815412e-310]])

In [4]:
import numpy as np

a = np.ndarray((3, 2), dtype=int)
a

array([[      191910544,               0],
       [135572147871600,        10856224],
       [       10869536, 135572148594160]])

In [5]:
a = np.ndarray((3, 2), int)
a

array([[      192348491,               0],
       [      190001584,       191944000],
       [135572126317056, 135572577839904]])

In [6]:
import numpy as np

a = np.array([1, 2, 3], dtype=int)
a

array([1, 2, 3])

In [10]:
type(a)

numpy.ndarray

In [11]:
print(a.shape)
print(a.ndim)
print(a.dtype)

(3,)
1
int64


In [12]:
print(a.size)
print(a.itemsize)
print(a.nbytes)

3
8
24


In [13]:
np.array([1, 'py', 3.14])

array(['1', 'py', '3.14'], dtype='<U32')

In [14]:
import numpy as np

unicode_array = np.array(['가나다', '라마바', '사아자'], dtype='<U32')
unicode_array

array(['가나다', '라마바', '사아자'], dtype='<U32')

In [16]:
unicode_array = np.array(['가나다라마'*7, '라마바', '사아자'], dtype='<U32')
unicode_array

array(['가나다라마가나다라마가나다라마가나다라마가나다라마가나다라마가나', '라마바', '사아자'], dtype='<U32')

In [17]:
import numpy as np

print(np.arange(3))
print(np.arange(3, 7))
print(np.arange(3, 7, 2))

[0 1 2]
[3 4 5 6]
[3 5]


In [18]:
import numpy as np

print(np.arange(2.0))
print(np.arange(2.0, 6.5))
print(np.arange(2.0, 6.5, 0.8))

[0. 1.]
[2. 3. 4. 5. 6.]
[2.  2.8 3.6 4.4 5.2 6. ]


In [19]:
import numpy as np

a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [20]:
np.reshape(a, (2, 6))

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [21]:
np.reshape(a, (3, 5))

ValueError: cannot reshape array of size 12 into shape (3,5)

In [23]:
np.linspace(2,0, 3.0)

TypeError: 'float' object cannot be interpreted as an integer

In [24]:
np.linspace(2.0, 3.0, retstep=True)

(array([2.        , 2.02040816, 2.04081633, 2.06122449, 2.08163265,
        2.10204082, 2.12244898, 2.14285714, 2.16326531, 2.18367347,
        2.20408163, 2.2244898 , 2.24489796, 2.26530612, 2.28571429,
        2.30612245, 2.32653061, 2.34693878, 2.36734694, 2.3877551 ,
        2.40816327, 2.42857143, 2.44897959, 2.46938776, 2.48979592,
        2.51020408, 2.53061224, 2.55102041, 2.57142857, 2.59183673,
        2.6122449 , 2.63265306, 2.65306122, 2.67346939, 2.69387755,
        2.71428571, 2.73469388, 2.75510204, 2.7755102 , 2.79591837,
        2.81632653, 2.83673469, 2.85714286, 2.87755102, 2.89795918,
        2.91836735, 2.93877551, 2.95918367, 2.97959184, 3.        ]),
 np.float64(0.02040816326530612))

In [25]:
print( (3-2) / (50-1) )

0.02040816326530612


In [26]:
np.linspace(2.0, 3.0, endpoint=False, retstep=True)

(array([2.  , 2.02, 2.04, 2.06, 2.08, 2.1 , 2.12, 2.14, 2.16, 2.18, 2.2 ,
        2.22, 2.24, 2.26, 2.28, 2.3 , 2.32, 2.34, 2.36, 2.38, 2.4 , 2.42,
        2.44, 2.46, 2.48, 2.5 , 2.52, 2.54, 2.56, 2.58, 2.6 , 2.62, 2.64,
        2.66, 2.68, 2.7 , 2.72, 2.74, 2.76, 2.78, 2.8 , 2.82, 2.84, 2.86,
        2.88, 2.9 , 2.92, 2.94, 2.96, 2.98]),
 np.float64(0.02))

In [27]:
print( (3-2) / 50 )

0.02


In [28]:
np.linspace(2.0, 3.0, num=5, retstep=True)

(array([2.  , 2.25, 2.5 , 2.75, 3.  ]), np.float64(0.25))

In [29]:
np.linspace(2.0, 3.0, num=5, endpoint=False, retstep=True)

(array([2. , 2.2, 2.4, 2.6, 2.8]), np.float64(0.2))

In [30]:
import numpy as np

a = np.zeros(5)
a

a.dtype

dtype('float64')

In [31]:
np.zeros((5,), dtype=int)

array([0, 0, 0, 0, 0])

In [33]:
b = np.zeros((2, 1))
b

array([[0.],
       [0.]])

In [34]:
np.ones((2, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [35]:
np.ones((2, 4), dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

In [36]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [37]:
np.eye(2, dtype=int)

array([[1, 0],
       [0, 1]])

In [38]:
np.eye(3, 4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [39]:
a = np.eye(3, 4, 1)
a

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [40]:
b = np.eye(3, 4, -1)
b

array([[0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.]])

In [42]:
np.full([2, 3], 10)

array([[10, 10, 10],
       [10, 10, 10]])

In [43]:
np.full([2, 3], (1, 2, 3))

array([[1, 2, 3],
       [1, 2, 3]])

In [44]:
np.full([2, 3], (1, 2))

ValueError: could not broadcast input array from shape (2,) into shape (2,3)

In [45]:
np.full([3, 4], range(4))

array([[0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3]])

In [46]:
np.full([4, 3], fill_value=np.arange(4).reshape(4, 1))

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

In [47]:
np.empty(3)

array([4.9e-324, 9.9e-324, 1.5e-323])

In [48]:
np.empty([2, 2])

array([[0.0e+000, 4.9e-324],
       [9.9e-324, 1.5e-323]])

In [52]:
np.empty([2, 3], dtype=int)

array([[225297872,         0,         0],
       [        0,         0,         0]])

In [53]:
import numpy as np

a = np.arange(8).reshape(2, 4)
a

np.zeros_like(a)

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [54]:
np.ones_like(a)

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

In [55]:
np.full_like(a, 5)

array([[5, 5, 5, 5],
       [5, 5, 5, 5]])

In [56]:
import numpy as np

a = np.arange(3)
a

array([0, 1, 2])

In [57]:
print(a + 2)
print(a - 2)
print(a * 2)
print(a / 2)

[2 3 4]
[-2 -1  0]
[0 2 4]
[0.  0.5 1. ]


In [58]:
a = np.arange(1, 7).reshape(2,3)
a

array([[1, 2, 3],
       [4, 5, 6]])

In [59]:
b = np.full_like(a, [1, 2, 3])
b

array([[1, 2, 3],
       [1, 2, 3]])

In [60]:
print(a + 2)
print(a - 2)
print(a * 2)
print(a / 2)

[[3 4 5]
 [6 7 8]]
[[-1  0  1]
 [ 2  3  4]]
[[ 2  4  6]
 [ 8 10 12]]
[[0.5 1.  1.5]
 [2.  2.5 3. ]]


In [61]:
a = np.arange(4)
a

array([0, 1, 2, 3])

In [62]:
b = np.arange(0.5, 4, 1)
b

array([0.5, 1.5, 2.5, 3.5])

In [63]:
a += b

UFuncTypeError: Cannot cast ufunc 'add' output from dtype('float64') to dtype('int64') with casting rule 'same_kind'

In [65]:
b += a
b

array([0.5, 3.5, 6.5, 9.5])

In [66]:
a = np.full((2, 3), [1, 2, 3])
a

array([[1, 2, 3],
       [1, 2, 3]])

In [67]:
b = np.full((3, 2), [2, 1])
b

array([[2, 1],
       [2, 1],
       [2, 1]])

In [68]:
a @ b

array([[12,  6],
       [12,  6]])

In [69]:
a.dot(b)

array([[12,  6],
       [12,  6]])

In [70]:
b.dot(a)

array([[3, 6, 9],
       [3, 6, 9],
       [3, 6, 9]])

In [71]:
import numpy as np
print(np.matmul(a, b))
print(np.matmul(b, a))

[[12  6]
 [12  6]]
[[3 6 9]
 [3 6 9]
 [3 6 9]]


In [72]:
a = np.array([[10, 20], [5, 8], [1, 2]])
a

array([[10, 20],
       [ 5,  8],
       [ 1,  2]])

In [73]:
a.sum()

np.int64(46)

In [74]:
a.sum(axis=0)

array([16, 30])

In [75]:
a.sum(axis=1)

array([30, 13,  3])

In [76]:
import numpy as np

print(np.sum(a))
print(np.sum(a, axis=0))
print(np.sum(a, axis=1))

46
[16 30]
[30 13  3]


In [77]:
a = np.array([[3, 5, 8], [1, 2, 3]])
a

array([[3, 5, 8],
       [1, 2, 3]])

In [78]:
a.cumsum()

array([ 3,  8, 16, 17, 19, 22])

In [79]:
a.cumsum(axis=0)

array([[ 3,  5,  8],
       [ 4,  7, 11]])

In [80]:
a.cumsum(axis=1)

array([[ 3,  8, 16],
       [ 1,  3,  6]])

In [81]:
import numpy as np

a = np.array([1, 4, 9])
a

array([1, 4, 9])

In [82]:
b = np.full_like(a, 2)
b

array([2, 2, 2])

In [83]:
np.add(a, b)

array([ 3,  6, 11])

In [84]:
np.divide(a, b)

array([0.5, 2. , 4.5])

In [85]:
np.power(a, b)

array([ 1, 16, 81])

In [87]:
import numpy as np

a = np.power(np.arange(10), 2)
a

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [88]:
print(a[3])
print(a[-2])

9
64


In [89]:
print(a[1:4])
print(a[-5:-1])

[1 4 9]
[25 36 49 64]


In [91]:
print(a[8:2:-1])
print(a[-1:-7:-1])

[64 49 36 25 16  9]
[81 64 49 36 25 16]


In [92]:
a[::-1]

array([81, 64, 49, 36, 25, 16,  9,  4,  1,  0])

In [93]:
a[::-2]

array([81, 49, 25,  9,  1])

In [95]:
a[2:5] = -100
a

array([   0,    1, -100, -100, -100,   25,   36,   49,   64,   81])

In [96]:
a[2:5] = [-5, -5, -5]
a

array([ 0,  1, -5, -5, -5, 25, 36, 49, 64, 81])

In [97]:
a[2:5] = [-5, -5]
a

ValueError: could not broadcast input array from shape (2,) into shape (3,)

In [98]:
a = np.arange(30).reshape(5, 6)
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [99]:
a[3]

array([18, 19, 20, 21, 22, 23])

In [100]:
a[-1]

array([24, 25, 26, 27, 28, 29])

In [101]:
a[-2, :]

array([18, 19, 20, 21, 22, 23])

In [102]:
a[-2, ]

array([18, 19, 20, 21, 22, 23])

In [103]:
a[2:4]

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [104]:
a[1:5:2]

array([[ 6,  7,  8,  9, 10, 11],
       [18, 19, 20, 21, 22, 23]])

In [105]:
a[, 1]

SyntaxError: invalid syntax (3063698125.py, line 1)

In [106]:
a[:, 1]

array([ 1,  7, 13, 19, 25])

In [107]:
a[:, 1:6]

array([[ 1,  2,  3,  4,  5],
       [ 7,  8,  9, 10, 11],
       [13, 14, 15, 16, 17],
       [19, 20, 21, 22, 23],
       [25, 26, 27, 28, 29]])

In [108]:
a = np.arange(30).reshape(5, 6)
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [109]:
a[:, ::2]

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16],
       [18, 20, 22],
       [24, 26, 28]])

In [110]:
a[2, 4]

np.int64(16)

In [111]:
a[2][4]

np.int64(16)

In [112]:
a[1:3, 2:5]

array([[ 8,  9, 10],
       [14, 15, 16]])

In [113]:
a[:, :]

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [114]:
a[:, ]

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [115]:
a[:]

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [116]:
a[::-1, ::-1]

array([[29, 28, 27, 26, 25, 24],
       [23, 22, 21, 20, 19, 18],
       [17, 16, 15, 14, 13, 12],
       [11, 10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1,  0]])

In [117]:
a[:-1, :-1]

array([[ 0,  1,  2,  3,  4],
       [ 6,  7,  8,  9, 10],
       [12, 13, 14, 15, 16],
       [18, 19, 20, 21, 22]])

In [118]:
a = np.arange(24).reshape(2, 3, 4)
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [119]:
a[1]

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [120]:
a[:, 1]

array([[ 4,  5,  6,  7],
       [16, 17, 18, 19]])

In [121]:
a[:, 1, 1]

array([ 5, 17])

In [122]:
a[:, :, 1]

array([[ 1,  5,  9],
       [13, 17, 21]])

In [123]:
a[..., 1]

array([[ 1,  5,  9],
       [13, 17, 21]])

In [124]:
a[1, ..., 1]

array([13, 17, 21])

In [125]:
a[0, ...]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [126]:
a[0]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [127]:
a = np.arange(12).reshape(2, 3, 2)
a

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [128]:
b = a.ravel()
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [129]:
a = np.arange(1, 7).reshape(2, 3)
a

array([[1, 2, 3],
       [4, 5, 6]])

In [130]:
np.transpose(a)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [132]:
a.transpose()

array([[1, 4],
       [2, 5],
       [3, 6]])

In [133]:
a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [134]:
b = np.arange(1, 13).reshape(3, 2, 2)
b

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [135]:
b.T

array([[[ 1,  5,  9],
        [ 3,  7, 11]],

       [[ 2,  6, 10],
        [ 4,  8, 12]]])

In [136]:
b = np.arange(1, 13).reshape(3, 2, 2)
b

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [137]:
np.transpose(b, (0, 1, 2))

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [138]:
np.transpose(b, (2, 1, 0))

array([[[ 1,  5,  9],
        [ 3,  7, 11]],

       [[ 2,  6, 10],
        [ 4,  8, 12]]])

In [139]:
np.transpose(b, (0, 2, 1))

array([[[ 1,  3],
        [ 2,  4]],

       [[ 5,  7],
        [ 6,  8]],

       [[ 9, 11],
        [10, 12]]])

In [140]:
x = np.array([[7, 8, 9]])
x

array([[7, 8, 9]])

In [141]:
y = np.swapaxes(x, 0, 1)
y

array([[7],
       [8],
       [9]])

In [142]:
y = np.swapaxes(x, 1, 0)
y

array([[7],
       [8],
       [9]])

In [143]:
y[0, 0] = 10
x

array([[10,  8,  9]])

In [144]:
x = np.array(np.arange(8).reshape(2, 2, 2))
x

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [146]:
np.swapaxes(x, 0, 2)

array([[[0, 4],
        [2, 6]],

       [[1, 5],
        [3, 7]]])

In [147]:
np.transpose(x, (2, 1, 0))

array([[[0, 4],
        [2, 6]],

       [[1, 5],
        [3, 7]]])

In [148]:
org = np.arange(5)
org

array([0, 1, 2, 3, 4])

In [149]:
v = org.view()
v

array([0, 1, 2, 3, 4])

In [150]:
v[2] = 200
v

array([  0,   1, 200,   3,   4])

In [151]:
org

array([  0,   1, 200,   3,   4])

In [152]:
org = np.arange(5)
org

array([0, 1, 2, 3, 4])

In [153]:
c = org.copy()
c

array([0, 1, 2, 3, 4])

In [154]:
c[2] = 200
c

array([  0,   1, 200,   3,   4])

In [155]:
org

array([0, 1, 2, 3, 4])

In [156]:
x = np.arange(6)
x

array([0, 1, 2, 3, 4, 5])

In [157]:
y = x.reshape(2, 3)
y

array([[0, 1, 2],
       [3, 4, 5]])

In [158]:
print(x.base)

None


In [159]:
y.base

array([0, 1, 2, 3, 4, 5])

In [160]:
z = y.transpose()
z.base

array([0, 1, 2, 3, 4, 5])

In [161]:
c = z.copy()
print(c.base)

None


In [162]:
lst = list(range(8))
lst

[0, 1, 2, 3, 4, 5, 6, 7]

In [163]:
lst[3:5] = [30, 40, 50]
lst

[0, 1, 2, 30, 40, 50, 5, 6, 7]

In [164]:
x = np.arange(8)
x

array([0, 1, 2, 3, 4, 5, 6, 7])

In [165]:
x[3:5] = [30, 40]
x

array([ 0,  1,  2, 30, 40,  5,  6,  7])

In [166]:
x[3:5] = [30, 40, 50]
x

ValueError: could not broadcast input array from shape (3,) into shape (2,)

In [167]:
a = np.array([[1, 2, 3], [4, 5, 6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [169]:
b = a
b is a

True

In [170]:
print(id(a))
print(id(b))

135571574004816
135571574004816


In [171]:
print(a.base)
print(b.base)

None
None


In [172]:
b[0, 0] = 100
a

array([[100,   2,   3],
       [  4,   5,   6]])

In [173]:
c = a.copy()
c

array([[100,   2,   3],
       [  4,   5,   6]])

In [175]:
print(id(a))
print(id(c))

135571574004816
135571574004912


In [176]:
print(c.base)

None


In [177]:
v = a.reshape(3, 2)
v

array([[100,   2],
       [  3,   4],
       [  5,   6]])

In [178]:
print(id(a))
print(id(v))

135571574004816
135571574004144


In [179]:
v[0, 1] = 200
a

array([[100, 200,   3],
       [  4,   5,   6]])

In [180]:
v.base

array([[100, 200,   3],
       [  4,   5,   6]])

In [181]:
a = np.array([3, 4, 5])
b = np.array([8, 7, 6])
a + b

array([11, 11, 11])

In [182]:
a = np.array([3, 4, 5, 7])
b = np.array([8, 7, 6])
a * b

ValueError: operands could not be broadcast together with shapes (4,) (3,) 

In [183]:
from numpy import arange
x = arange(1, 10).reshape(3, 3)
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [186]:
y = arange(-1, 2)
y

array([-1,  0,  1])

In [187]:
x * y

array([[-1,  0,  3],
       [-4,  0,  6],
       [-7,  0,  9]])

In [188]:
x + y

array([[ 0,  2,  4],
       [ 3,  5,  7],
       [ 6,  8, 10]])

In [189]:
from numpy import arange

x = arange(1, 10).reshape(3, 3)
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [190]:
y = arange(3, 10, 3)/reshape(3, 1)
y

NameError: name 'reshape' is not defined

In [191]:
np.set_printoptions(precision=2)

In [192]:
x / y

/tmp/ipykernel_503/3016948717.py:1: RuntimeWarning: divide by zero encountered in divide
  x / y


array([[-1., inf,  3.],
       [-4., inf,  6.],
       [-7., inf,  9.]])

In [193]:
x - y

array([[2, 2, 2],
       [5, 5, 5],
       [8, 8, 8]])

In [194]:
from numpy import arange

x = arange(1, 4)
x

array([1, 2, 3])

In [195]:
y = arange(1, 4).reshape(3, 1)
y

array([[1],
       [2],
       [3]])

In [196]:
x * y

array([[1, 2, 3],
       [2, 4, 6],
       [3, 6, 9]])

In [197]:
x / y

array([[1.  , 2.  , 3.  ],
       [0.5 , 1.  , 1.5 ],
       [0.33, 0.67, 1.  ]])

In [198]:
from numpy import arange

x = arange(0, 10, 3).reshape(4, 1)
x

array([[0],
       [3],
       [6],
       [9]])

In [199]:
y = arange(1, 3)
y

array([1, 2])

In [200]:
x * y

array([[ 0,  0],
       [ 3,  6],
       [ 6, 12],
       [ 9, 18]])

In [201]:
x + y

array([[ 1,  2],
       [ 4,  5],
       [ 7,  8],
       [10, 11]])

In [202]:
import numpy as np
from numpy import array
x = array([0, 10, 20, 30])
x

array([ 0, 10, 20, 30])

In [203]:
np.newaxis is None

True

In [204]:
a = x[None, :]
a

array([[ 0, 10, 20, 30]])

In [205]:
a = x[np.newaxis, :]
a

array([[ 0, 10, 20, 30]])

In [206]:
a = x[:, np.newaxis]
a

array([[ 0],
       [10],
       [20],
       [30]])

In [207]:
a.shape

(4, 1)

In [208]:
from numpy import array

b = array([1, 2, 3])
b

array([1, 2, 3])

In [209]:
a + b

array([[ 1,  2,  3],
       [11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [210]:
a * b

array([[ 0,  0,  0],
       [10, 20, 30],
       [20, 40, 60],
       [30, 60, 90]])

In [211]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [212]:
print(x[1])
print(x[:5])

1
[0 1 2 3 4]


In [214]:
print(x[[2]])
print(x[[2, 3]])

[2]
[2 3]


In [215]:
x[[2, 3, 5, 8]]

array([2, 3, 5, 8])

In [216]:
x[np.array([5, 3, -4, 8])]

array([5, 3, 6, 8])

In [217]:
from numpy import arange

x = arange(56).reshape(7, 8)
x

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55]])

In [218]:
x[0]

array([0, 1, 2, 3, 4, 5, 6, 7])

In [219]:
x[0, 1]

np.int64(1)

In [220]:
x[:, 2:8]

array([[ 2,  3,  4,  5,  6,  7],
       [10, 11, 12, 13, 14, 15],
       [18, 19, 20, 21, 22, 23],
       [26, 27, 28, 29, 30, 31],
       [34, 35, 36, 37, 38, 39],
       [42, 43, 44, 45, 46, 47],
       [50, 51, 52, 53, 54, 55]])

In [221]:
x[, 2:8]

SyntaxError: invalid syntax (664993225.py, line 1)

In [222]:
x[[0], [1]]

array([1])

In [223]:
x[[0, 1]]

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [224]:
x[:, [5, 4]]

array([[ 5,  4],
       [13, 12],
       [21, 20],
       [29, 28],
       [37, 36],
       [45, 44],
       [53, 52]])

In [225]:
x[[1, 3]]

array([[ 8,  9, 10, 11, 12, 13, 14, 15],
       [24, 25, 26, 27, 28, 29, 30, 31]])

In [226]:
x[[1, 3], :]

array([[ 8,  9, 10, 11, 12, 13, 14, 15],
       [24, 25, 26, 27, 28, 29, 30, 31]])

In [227]:
from numpy import arange

x = arange(56).reshape(7, 8)
x

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55]])

In [228]:
x[[1, 3], [2, 2]]

array([10, 26])

In [229]:
x[[1, 3], [2]]

array([10, 26])

In [230]:
x[[1, 3], 2]

array([10, 26])

In [231]:
from numpy import arange

x = arange(56).reshape(7, 8)
x

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55]])

In [232]:
x[np.array([0, 2, 4]), 1]

array([ 1, 17, 33])

In [233]:
print(x[0, 1])
print(x[2, 1])
print(x[4, 1])

1
17
33


In [235]:
x[array([0, 2,4]), :2]

array([[ 0,  1],
       [16, 17],
       [32, 33]])

In [236]:
from numpy import array

x[array([0, 2, 4]). array([0, 1])]

AttributeError: 'numpy.ndarray' object has no attribute 'array'

In [237]:
from numpy import arange

a = arange(40).reshape(5, 8)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39]])

In [238]:
a[2:4, 3:7]

array([[19, 20, 21, 22],
       [27, 28, 29, 30]])

In [239]:
a[arange(2, 4)]

array([[16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31]])

In [240]:
from numpy import arange

a = arange(40).reshape(5, 8)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39]])

In [241]:
a[arange(2, 4)][:, [1, 0]]

array([[17, 16],
       [25, 24]])

In [242]:
a[arange(2, 5)][:, [1, 0, 3, 5]]

array([[17, 16, 19, 21],
       [25, 24, 27, 29],
       [33, 32, 35, 37]])

In [243]:
a[arange(2, 5)]

array([[16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39]])

In [244]:
a[arange(2, 5)][:, arange(-1, -8, -1)]

array([[23, 22, 21, 20, 19, 18, 17],
       [31, 30, 29, 28, 27, 26, 25],
       [39, 38, 37, 36, 35, 34, 33]])