<a href="https://colab.research.google.com/github/kimjaewoo1207/2026_1_BDA/blob/main/%EB%B9%85%EB%8D%B0%EC%9D%B4%ED%84%B0%EB%B6%84%EC%84%9D%ED%94%84%EB%A1%9C%EA%B7%B8%EB%9E%98%EB%B0%8D4%EC%A3%BC%EC%B0%A8_52%ED%8E%98%EC%9D%B4%EC%A7%80%EB%B6%80%ED%84%B0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

a = np.arange(6).reshape(3, 2)
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [2]:
b = np.arange(6, 12).reshape(3,2)
b

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [3]:
np.vstack((a, b))

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [4]:
import numpy as np

x = np.array([1, 2, 3])
y = np.array([5, 6, 7])
np.vstack((x, y))

array([[1, 2, 3],
       [5, 6, 7]])

In [5]:
import numpy as np

a = np.arange(6).reshape(3, 2)
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [6]:
b = np.arange(10, 19).reshape(3, 3)
b

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [7]:
np.hstack((a, b))

array([[ 0,  1, 10, 11, 12],
       [ 2,  3, 13, 14, 15],
       [ 4,  5, 16, 17, 18]])

In [8]:
np.hstack((np.arange(3), np.arange(10, 15)))

array([ 0,  1,  2, 10, 11, 12, 13, 14])

In [9]:
x = np.array([1, 2, 3])
y = np.array([10, 20, 30])
np.column_stack((x, y))

array([[ 1, 10],
       [ 2, 20],
       [ 3, 30]])

In [10]:
x[:, np.newaxis]

array([[1],
       [2],
       [3]])

In [11]:
x = np.array([1, 2, 3])
y = np.array([10, 20, 30])
np.column_stack((x[:, np.newaxis], y[:, np.newaxis]))

array([[ 1, 10],
       [ 2, 20],
       [ 3, 30]])

In [12]:
np.hstack((x, y))

array([ 1,  2,  3, 10, 20, 30])

In [13]:
np.column_stack == np.hstack

False

In [14]:
import numpy as np

a = np.arange(6).reshape(2, 3)
a

array([[0, 1, 2],
       [3, 4, 5]])

In [15]:
b = np.arange(10, 22).reshape(4, 3)
b

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21]])

In [16]:
np.row_stack((a, b))

/tmp/ipykernel_1447/2094407319.py:1: DeprecationWarning: `row_stack` alias is deprecated. Use `np.vstack` directly.
  np.row_stack((a, b))


array([[ 0,  1,  2],
       [ 3,  4,  5],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21]])

In [17]:
import numpy as np

a = np.array([1, 2])
b = np.array([3, 4])
c = np.array([5, 6])

In [18]:
np.concatenate((a, b, c))

array([1, 2, 3, 4, 5, 6])

In [19]:
np.concatenate((a, b, c), axis=0)

array([1, 2, 3, 4, 5, 6])

In [20]:
np.concat((a, b, c), axis=None)

array([1, 2, 3, 4, 5, 6])

In [21]:
import numpy as np

x = np.arange(6).reshape(2, 3)
x

array([[0, 1, 2],
       [3, 4, 5]])

In [22]:
y = np.arange(10, 16).reshape(2, 3)
y

array([[10, 11, 12],
       [13, 14, 15]])

In [24]:
z = np.arange(20, 24).reshape(2, 2)
z

array([[20, 21],
       [22, 23]])

In [25]:
np.concatenate((x, y))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [10, 11, 12],
       [13, 14, 15]])

In [26]:
np.concatenate((x, y), axis=1)

array([[ 0,  1,  2, 10, 11, 12],
       [ 3,  4,  5, 13, 14, 15]])

In [27]:
np.concatenate((x, y, z), axis=1)

array([[ 0,  1,  2, 10, 11, 12, 20, 21],
       [ 3,  4,  5, 13, 14, 15, 22, 23]])

In [28]:
np.concatenate((x, y), axis=None)

array([ 0,  1,  2,  3,  4,  5, 10, 11, 12, 13, 14, 15])

In [29]:
import numpy as np

a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [30]:
b = np.array([4, 5, 6])
b

array([4, 5, 6])

In [31]:
np.stack((a, b))

array([[1, 2, 3],
       [4, 5, 6]])

In [32]:
np.stack((a, b), axis=1)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [33]:
np.stack((a, b), axis=-1)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [34]:
np.arange(1, 19).reshape(3, 3, 2)

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]],

       [[13, 14],
        [15, 16],
        [17, 18]]])

In [35]:
np.arange(16).reshape(2, 2, 4)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [36]:
x = np.arange(6).reshape(2, 3)
x

array([[0, 1, 2],
       [3, 4, 5]])

In [37]:
y = np.arange(10, 16).reshape(2, 3)
y

array([[10, 11, 12],
       [13, 14, 15]])

In [38]:
z = np.arange(20, 26).reshape(2, 3)
z

array([[20, 21, 22],
       [23, 24, 25]])

In [39]:
ax0 = np.stack((x, y, z), axis=0)
ax0

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[10, 11, 12],
        [13, 14, 15]],

       [[20, 21, 22],
        [23, 24, 25]]])

In [40]:
ax0.shape

(3, 2, 3)

In [41]:
x = np.arange(6).reshape(2, 3)
x

array([[0, 1, 2],
       [3, 4, 5]])

In [42]:
y = np.arange(10, 16).reshape(2, 3)
y

array([[10, 11, 12],
       [13, 14, 15]])

In [43]:
z = np.arange(20, 26).reshape(2, 3)
z

array([[20, 21, 22],
       [23, 24, 25]])

In [44]:
ax1 = np.stack((x, y, z), axis=1)
ax1

array([[[ 0,  1,  2],
        [10, 11, 12],
        [20, 21, 22]],

       [[ 3,  4,  5],
        [13, 14, 15],
        [23, 24, 25]]])

In [45]:
ax1.shape

(2, 3, 3)

In [46]:
x = np.arange(6).reshape(2, 3)
x

array([[0, 1, 2],
       [3, 4, 5]])

In [47]:
y = np.arange(10, 16).reshape(2, 3)
y

array([[10, 11, 12],
       [13, 14, 15]])

In [48]:
z = np.arange(20, 26).reshape(2, 3)
z

array([[20, 21, 22],
       [23, 24, 25]])

In [49]:
ax2 = np.stack((x, y, z), axis=2)
ax2

array([[[ 0, 10, 20],
        [ 1, 11, 21],
        [ 2, 12, 22]],

       [[ 3, 13, 23],
        [ 4, 14, 24],
        [ 5, 15, 25]]])

In [50]:
ax2.shape

(2, 3, 3)

In [51]:
print(x, '\n')
print(y, '\n')
print(z, '\n')

[[0 1 2]
 [3 4 5]] 

[[10 11 12]
 [13 14 15]] 

[[20 21 22]
 [23 24 25]] 



In [52]:
print('np.stack((x, y, z), axis=0)')
print(np.stack((x, y, z), axis=0))
print('np.stack((x, y, z), axis=1)')
print(np.stack((x, y, z), axis=1))
print('np.stack((x, y, z), axis=2)')
print(np.stack((x, y, z), axis=2))

np.stack((x, y, z), axis=0)
[[[ 0  1  2]
  [ 3  4  5]]

 [[10 11 12]
  [13 14 15]]

 [[20 21 22]
  [23 24 25]]]
np.stack((x, y, z), axis=1)
[[[ 0  1  2]
  [10 11 12]
  [20 21 22]]

 [[ 3  4  5]
  [13 14 15]
  [23 24 25]]]
np.stack((x, y, z), axis=2)
[[[ 0 10 20]
  [ 1 11 21]
  [ 2 12 22]]

 [[ 3 13 23]
  [ 4 14 24]
  [ 5 15 25]]]


In [53]:
x

array([[0, 1, 2],
       [3, 4, 5]])

In [54]:
y

array([[10, 11, 12],
       [13, 14, 15]])

In [55]:
z

array([[20, 21, 22],
       [23, 24, 25]])

In [56]:
x[:, :, np.newaxis]

array([[[0],
        [1],
        [2]],

       [[3],
        [4],
        [5]]])

In [57]:
y[:, :, np.newaxis]

array([[[10],
        [11],
        [12]],

       [[13],
        [14],
        [15]]])

In [58]:
z[:, :, np.newaxis]

array([[[20],
        [21],
        [22]],

       [[23],
        [24],
        [25]]])

In [59]:
np.expand_dims(x, axis=2)

array([[[0],
        [1],
        [2]],

       [[3],
        [4],
        [5]]])

In [60]:
np.expand_dims(y, axis=2)

array([[[10],
        [11],
        [12]],

       [[13],
        [14],
        [15]]])

In [61]:
np.expand_dims(z, axis=2)

array([[[20],
        [21],
        [22]],

       [[23],
        [24],
        [25]]])

In [63]:
np.stack((x, y, z), axis=2)

array([[[ 0, 10, 20],
        [ 1, 11, 21],
        [ 2, 12, 22]],

       [[ 3, 13, 23],
        [ 4, 14, 24],
        [ 5, 15, 25]]])

In [70]:
import numpy as np

a = np.arange(1, 13).reshape(3, 4)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [71]:
b = np.arange(1, 5)
b

array([1, 2, 3, 4])

In [72]:
np.row_stack((a, b))

/tmp/ipykernel_1447/2094407319.py:1: DeprecationWarning: `row_stack` alias is deprecated. Use `np.vstack` directly.
  np.row_stack((a, b))


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [ 1,  2,  3,  4]])

In [73]:
np.vstack((a, b))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [ 1,  2,  3,  4]])

In [74]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

result = np.c_[a, b]
print(result)

[[1 4]
 [2 5]
 [3 6]]


In [75]:
np.r_['-1, 2, 0', a, b]

array([[1, 4],
       [2, 5],
       [3, 6]])

In [76]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array((4, 5, 6))

In [77]:
np.c_[a, b]

array([[1, 4],
       [2, 5],
       [3, 6]])

In [78]:
np.column_stack((a, b))

array([[1, 4],
       [2, 5],
       [3, 6]])

In [79]:
x = np.array([[1, 2, 3]])
y = np.array([[4, 5, 6]])

In [80]:
np.c_[x, y]

array([[1, 2, 3, 4, 5, 6]])

In [81]:
np.column_stack((x, y))

array([[1, 2, 3, 4, 5, 6]])

In [82]:
np.c_[x, 10, 20, y]

array([[ 1,  2,  3, 10, 20,  4,  5,  6]])

In [83]:
np.column_stack((x, 10, 20, y))

array([[ 1,  2,  3, 10, 20,  4,  5,  6]])

In [84]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array((4, 5, 6))

In [85]:
np.r_[a, b]

array([1, 2, 3, 4, 5, 6])

In [86]:
np.hstack((a, b))

array([1, 2, 3, 4, 5, 6])

In [87]:
np.row_stack((a, b))

/tmp/ipykernel_1447/2094407319.py:1: DeprecationWarning: `row_stack` alias is deprecated. Use `np.vstack` directly.
  np.row_stack((a, b))


array([[1, 2, 3],
       [4, 5, 6]])

In [88]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array((4, 5, 6))

In [89]:
np.r_[a, 0, 0, b]

array([1, 2, 3, 0, 0, 4, 5, 6])

In [90]:
np.r_[3:10:3, [0]*2, 5, 6]

array([3, 6, 9, 0, 0, 5, 6])

In [91]:
np.r_[-1:1:6j, [0]*2, 5, 6]

array([-1. , -0.6, -0.2,  0.2,  0.6,  1. ,  0. ,  0. ,  5. ,  6. ])

In [93]:
np.linspace(-1, 1, 6)

array([-1. , -0.6, -0.2,  0.2,  0.6,  1. ])

In [94]:
a = np.array([[0, 1, 2], [3, 4, 5]])
a

array([[0, 1, 2],
       [3, 4, 5]])

In [95]:
np.r_[a, a, a]

array([[0, 1, 2],
       [3, 4, 5],
       [0, 1, 2],
       [3, 4, 5],
       [0, 1, 2],
       [3, 4, 5]])

In [97]:
np.r_['0', a, a]

array([[0, 1, 2],
       [3, 4, 5],
       [0, 1, 2],
       [3, 4, 5]])

In [98]:
np.r_['-1', a, a]

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5]])

In [99]:
np.r_['1', a, a]

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5]])

In [101]:
np.r_['0, 2', a, a]

array([[0, 1, 2],
       [3, 4, 5],
       [0, 1, 2],
       [3, 4, 5]])

In [102]:
a = np.array([[0, 1, 2, [3, 4, 5]]])
a

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 2 dimensions. The detected shape was (1, 4) + inhomogeneous part.

In [103]:
np.r_['0, 2', [1, 2, 3], [4, 5, 6]]

array([[1, 2, 3],
       [4, 5, 6]])

In [104]:
np.r_['0, 2, 1', [1, 2, 3], [4, 5, 6]]

array([[1, 2, 3],
       [4, 5, 6]])

In [105]:
np.r_['0, 3', [1, 2, 3], [4, 5, 6]]

array([[[1, 2, 3]],

       [[4, 5, 6]]])

In [106]:
print(np.r_['0, 3, 2', [1, 2, 3], [4, 5, 6]])

[[[1 2 3]]

 [[4 5 6]]]


In [108]:
arr = np.array([1, 2, 3])
print(arr[np.newaxis, :])
print(arr[np.newaxis, :].shape, '\n')
print(arr[:, np.newaxis])
print(arr[:, np.newaxis].shape)

[[1 2 3]]
(1, 3) 

[[1]
 [2]
 [3]]
(3, 1)


In [109]:
np.expand_dims(arr, 0)

array([[1, 2, 3]])

In [110]:
np.expand_dims(arr, 1)

array([[1],
       [2],
       [3]])

In [111]:
np.r_[[1, 2, 3], [4, 5, 6]]

array([1, 2, 3, 4, 5, 6])

In [112]:
np.r_['0, 2, 0', [1, 2, 3], [4, 5, 6]]

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [113]:
np.r_['1, 2, 0', [1, 2, 3], [4, 5, 6]]

array([[1, 4],
       [2, 5],
       [3, 6]])

In [114]:
np.r_['0, 2, 1', [1, 2, 3], [4, 5, 6]]

array([[1, 2, 3],
       [4, 5, 6]])

In [115]:
np.r_['1, 2, 1', [1, 2, 3], [4, 5, 6]]

array([[1, 2, 3, 4, 5, 6]])

In [116]:
a = np.array([1, 2, 3])
a.shape

(3,)

In [117]:
print(np.expand_dims(a, axis=(0, 1)))
print(np.expand_dims(a, axis=(0, 1)).shape)

[[[1 2 3]]]
(1, 1, 3)


In [118]:
print(np.expand_dims(a, axis=(0, 2)))
print(np.expand_dims(a, axis=(0, 2)).shape)

[[[1]
  [2]
  [3]]]
(1, 3, 1)


In [120]:
print(np.expand_dims(a, axis=(1, 2)))
print(np.expand_dims(a, axis=(1, 2)).shape)

[[[1]]

 [[2]]

 [[3]]]
(3, 1, 1)


In [121]:
np.expand_dims(np.array([1, 2, 3]), axis=(1, 2))

array([[[1]],

       [[2]],

       [[3]]])

In [122]:
np.expand_dims(np.array([4, 5, 6]), axis=(1, 2))

array([[[4]],

       [[5]],

       [[6]]])

In [123]:
np.r_['0, 3, 0', [1, 2, 3], [ 4, 5, 6]]

array([[[1]],

       [[2]],

       [[3]],

       [[4]],

       [[5]],

       [[6]]])

In [126]:
np.r_['0, 3, 0', [1, 2, 3], [4, 5, 6]].shape

(6, 1, 1)

In [127]:
np.r_['0, 3, 1', [1, 2, 3], [4, 5, 6]]

array([[[1],
        [2],
        [3]],

       [[4],
        [5],
        [6]]])

In [128]:
print(np.expand_dims(np.array([1, 2, 3]), axis=(0, 2)))
print(np.expand_dims(np.array([4, 5, 6]), axis=(0, 2)))

[[[1]
  [2]
  [3]]]
[[[4]
  [5]
  [6]]]


In [129]:
np.r_['0, 3, 1', [1, 2, 3], [4, 5, 6]].shape

(2, 3, 1)

In [130]:
np.r_['0, 3, 2', [1, 2, 3], [4, 5, 6]]

array([[[1, 2, 3]],

       [[4, 5, 6]]])

In [131]:
print(np.expand_dims(np.array([1, 2, 3]), axis=(0, 1)))
print(np.expand_dims(np.array([4, 5, 6]), axis=(0, 1)))

[[[1 2 3]]]
[[[4 5 6]]]


In [132]:
np.r_['0, 3, 2', [1, 2, 3], [4, 5, 6]].shape

(2, 1, 3)

In [133]:
import numpy as np
a = np.matrix('1 2; 3 4')
a

matrix([[1, 2],
        [3, 4]])

In [134]:
type(a)

numpy.matrix

In [135]:
b = np.matrix([[1, 3], [3, 2]])
b

matrix([[1, 3],
        [3, 2]])

In [136]:
a * b

matrix([[ 7,  7],
        [15, 17]])

In [137]:
a @ b

matrix([[ 7,  7],
        [15, 17]])

In [138]:
print(np.r_[[[1, 2, 3]], [[4, 5, 6]]])

np.r_['r', [[1, 2, 3]], [[4, 5, 6]]]

[[1 2 3]
 [4 5 6]]


matrix([[1, 2, 3],
        [4, 5, 6]])

In [139]:
np.r_['c', [[1, 2, 3]], [[4, 5, 6]]]

matrix([[1, 2, 3],
        [4, 5, 6]])

In [140]:
print(np.r_[[1, 2, 3], [4, 5, 6]])

np.r_['r', [1, 2, 3], [4, 5, 6]]

[1 2 3 4 5 6]


matrix([[1, 2, 3, 4, 5, 6]])

In [142]:
print(np.r_[[1, 2, 3], [4, 5, 6]])

np.r_['c', [1, 2, 3], [4, 5, 6]]

[1 2 3 4 5 6]


matrix([[1],
        [2],
        [3],
        [4],
        [5],
        [6]])

In [143]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])


In [144]:
np.hstack((a, b))

array([1, 2, 3, 4, 5, 6])

In [146]:
np.r_[a, b]

array([1, 2, 3, 4, 5, 6])

In [147]:
np.concatenate((a, b))

array([1, 2, 3, 4, 5, 6])

In [148]:
np.c_[a, b]

array([[1, 4],
       [2, 5],
       [3, 6]])

In [149]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

In [151]:
np.vstack((a, b))

array([[1, 2, 3],
       [4, 5, 6]])

In [152]:
np.row_stack((a, b))

/tmp/ipykernel_1447/2094407319.py:1: DeprecationWarning: `row_stack` alias is deprecated. Use `np.vstack` directly.
  np.row_stack((a, b))


array([[1, 2, 3],
       [4, 5, 6]])

In [153]:
np.r_[a[np.newaxis, :], b[np.newaxis, :]]

array([[1, 2, 3],
       [4, 5, 6]])

In [154]:
np.concatenate((a[np.newaxis, :], b[np.newaxis, :]))

array([[1, 2, 3],
       [4, 5, 6]])

In [155]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

In [156]:
np.column_stack((a, b))

array([[1, 4],
       [2, 5],
       [3, 6]])

In [157]:
np.hstack((a[:, np.newaxis], b[:, np.newaxis]))

array([[1, 4],
       [2, 5],
       [3, 6]])

In [158]:
np.c_[a, b]

array([[1, 4],
       [2, 5],
       [3, 6]])

In [159]:
np.concatenate(((a[:, np.newaxis], b[:, np.newaxis])), axis=1)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [161]:
import numpy as np

x = np.arange(9.0)
x

array([0., 1., 2., 3., 4., 5., 6., 7., 8.])

In [162]:
s = np.split(x, 3)
s

[array([0., 1., 2.]), array([3., 4., 5.]), array([6., 7., 8.])]

In [163]:
import numpy as np
y = np.arange(10, 61, 10)
y

array([10, 20, 30, 40, 50, 60])

In [164]:
np.split(y, [2, 3, 4, 6])

[array([10, 20]),
 array([30]),
 array([40]),
 array([50, 60]),
 array([], dtype=int64)]

In [166]:
x = np.arange(1, 10)
x

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [167]:
np.split(x, [2, 6])

[array([1, 2]), array([3, 4, 5, 6]), array([7, 8, 9])]